# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll_test_plugin_malicious"
gem "jekyll-v4-github-pages", :require => "github-pages", :group => :jekyll_plugins, :path => "../../"

# Whitelisted plugins not included in runtime dependencies.
gem "jekyll-octicons", :group => :jekyll_plugins
